### ISSUE TITLE
How to create a new projext?

### ISSUE THREAD

**Issue by Anivie** [MarioAriasC/zig-support#38]
Okay, this question may seem silly, but I didn't see Zig's option in Clion's "New Project" option, and there is nothing about it in readme.
The version of plugin and Clion is latest.

**Comment by MarioAriasC** [comment]
Currently, there is no feature to create projects from the IDE.

Just use the command line:

```shell
zig init-exe
```
or

```shell
zig init-lib
```

And open the directory on CLion.

Maybe in the future I'll add that feature
